/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author Luis Gustavo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Menu() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Regist = new javax.swing.JButton();
        Busq = new javax.swing.JButton();
        Hist = new javax.swing.JButton();
        CheckIn = new javax.swing.JButton();
        CheckOut = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Regist.setText("Registro de clientes");
        Regist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistActionPerformed(evt);
            }
        });
        getContentPane().add(Regist, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 180, 60));

        Busq.setText("Busqueda de reservacion");
        Busq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Busq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusqActionPerformed(evt);
            }
        });
        getContentPane().add(Busq, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 180, 60));

        Hist.setText("Historial de habitacion");
        Hist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistActionPerformed(evt);
            }
        });
        getContentPane().add(Hist, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 180, 60));

        CheckIn.setText("Check-In");
        CheckIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInActionPerformed(evt);
            }
        });
        getContentPane().add(CheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 180, 60));

        CheckOut.setText("Check-Out");
        CheckOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutActionPerformed(evt);
            }
        });
        getContentPane().add(CheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 180, 60));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngtree-light-blue-background-gradient-abstract-background-halo-image_758338.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistActionPerformed
        Functions f = new Functions();
        f.HistorialHabitacion();
    }//GEN-LAST:event_HistActionPerformed

    private void RegistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistActionPerformed
        Functions f = new Functions();
        f.HistorialHabitacion();
    }//GEN-LAST:event_RegistActionPerformed

    private void BusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusqActionPerformed
        Functions f = new Functions();
        f.BusquedaReservacion();
    }//GEN-LAST:event_BusqActionPerformed

    private void CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutActionPerformed
        Functions f = new Functions();
        f.CheckOut();
    }//GEN-LAST:event_CheckOutActionPerformed

    private void CheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInActionPerformed
        Functions f = new Functions();
        f.CheckOut();
    }//GEN-LAST:event_CheckInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Busq;
    private javax.swing.JButton CheckIn;
    private javax.swing.JButton CheckOut;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Hist;
    private javax.swing.JButton Regist;
    // End of variables declaration//GEN-END:variables
}
