/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;


import static Interface.RegistroClientes.v2;
import javax.swing.JOptionPane;

public class Reservaciones extends javax.swing.JFrame {

    public static Menu v1;
    private String sexo;
    private String tipo_habitacion;

    
    public Reservaciones(Menu v1) {
        initComponents();
        this.v1 = v1;
        v1.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TITULO_Principal = new javax.swing.JLabel();
        TITULO_cedulaclient = new javax.swing.JLabel();
        input_ci = new javax.swing.JTextField();
        TITULO_filtrarName = new javax.swing.JLabel();
        input_filtrarName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        input_lastname = new javax.swing.JTextField();
        TITULO_sexo = new javax.swing.JLabel();
        TITULO_tipoEstudio = new javax.swing.JLabel();
        comb_estudio = new javax.swing.JComboBox<>();
        Volver = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Fecha_llegada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        Reservar = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO_Principal.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TITULO_Principal.setText("Reservaciones");
        jPanel1.add(TITULO_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        TITULO_cedulaclient.setText("Cedula del Cliente");
        jPanel1.add(TITULO_cedulaclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 20));
        jPanel1.add(input_ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, -1));

        TITULO_filtrarName.setText("Nombre");
        jPanel1.add(TITULO_filtrarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));
        jPanel1.add(input_filtrarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 160, -1));

        jLabel2.setText("Segundo Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 20));
        jPanel1.add(input_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 160, -1));

        TITULO_sexo.setText("Sexo:");
        jPanel1.add(TITULO_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        TITULO_tipoEstudio.setText("Tipo de Habitaion");
        jPanel1.add(TITULO_tipoEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, 20));

        comb_estudio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Doble", "Triple", "Suite" }));
        comb_estudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_estudioActionPerformed(evt);
            }
        });
        jPanel1.add(comb_estudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 80, 20));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 160, -1));

        jLabel1.setText("Email");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel3.setText("Celular:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 190, -1));

        jLabel4.setText("Fecha de salida:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));
        jPanel1.add(Fecha_llegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 170, -1));

        jLabel5.setText("Fecha de llegada:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 160, -1));

        Reservar.setText("Reservar");
        Reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarActionPerformed(evt);
            }
        });
        jPanel1.add(Reservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 110, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.setVisible(false);
        Menu ventana1 = new Menu(v2);
        ventana1.setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void comb_estudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_estudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comb_estudioActionPerformed

    private void ReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarActionPerformed
//        if (combo_edad.getSelectedItem() == "Tercera Edad"){
//            fc.tercera_edad(lista_registro);
//        }else if(combo_edad.getSelectedItem() == "Niños"){
//            fc.niños(lista_registro);
//        }else if(combo_edad.getSelectedItem() == "Adulto"){
//            fc.adulto(lista_registro);
//        }else{
//            fc.adolescente(lista_registro);
//        }
    }//GEN-LAST:event_ReservarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservaciones(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Fecha_llegada;
    private javax.swing.JButton Reservar;
    private javax.swing.JLabel TITULO_Principal;
    private javax.swing.JLabel TITULO_cedulaclient;
    private javax.swing.JLabel TITULO_filtrarName;
    private javax.swing.JLabel TITULO_sexo;
    private javax.swing.JLabel TITULO_tipoEstudio;
    private javax.swing.JButton Volver;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> comb_estudio;
    private javax.swing.JTextField input_ci;
    private javax.swing.JTextField input_filtrarName;
    private javax.swing.JTextField input_lastname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
