/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import EDD.ArbolBinario;
import EDD.Hashtable;
import EDD.ListaSimple;
import EDD.Precargar;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Gustavo
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public static Hashtable table = new Hashtable();
    public static ListaSimple lista_reservacion= new ListaSimple();
    public static ListaSimple lista_habitacion= new ListaSimple();
    public static ArbolBinario historial_habitacion = new ArbolBinario();
    
    public Welcome() {
        initComponents();
        this.setVisible(true);
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hotel = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hotel.setBackground(new java.awt.Color(0, 0, 0));
        hotel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        hotel.setText("¡BIENVENIDO! Pulse siguiente:");
        getContentPane().add(hotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 290, 30));

        welcome.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        welcome.setText("HOTEL UNIMET");
        getContentPane().add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, 30));

        next.setText("Siguente");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 130, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngtree-light-blue-background-gradient-abstract-background-halo-image_758338.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        Precargar fc_precargar = new Precargar();
        fc_precargar.Leer_Estado(table);
        fc_precargar.Leer_reservas(lista_reservacion);
        fc_precargar.Leer_habitaciones(lista_habitacion);
        JOptionPane.showMessageDialog(null,"Espere...");
        JOptionPane.showMessageDialog(null,"Datos Cargados.");
        
        Menu v2 = new Menu(this);
        v2.setVisible(true);
       
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel hotel;
    private javax.swing.JButton next;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
