/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.Cliente;
import Clases.Estado;
import EDD.ArbolBinario;
import EDD.Hashtable;
import EDD.ListaSimple;
import Funciones.Funciones;
import Funciones.Precargar;

/**
 *
 * @author gabri
 */
public class Menu extends javax.swing.JFrame {

    public static Inicio v1;
    
    public Menu(Inicio v1) {
        initComponents();
        this.v1 = v1;
        v1.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Registro = new javax.swing.JButton();
        Historial = new javax.swing.JButton();
        reservacion = new javax.swing.JButton();
        Check_Out = new javax.swing.JButton();
        Check_In = new javax.swing.JButton();
        Search1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 60, 50));

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 1, 48)); // NOI18N
        jLabel1.setText("Menu Principal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        Registro.setText("Registro de clientes");
        Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroActionPerformed(evt);
            }
        });
        jPanel1.add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 190, 60));

        Historial.setText("Historial de Habitacion");
        Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialActionPerformed(evt);
            }
        });
        jPanel1.add(Historial, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 190, 60));

        reservacion.setText("Reservacion");
        reservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservacionActionPerformed(evt);
            }
        });
        jPanel1.add(reservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 190, 60));

        Check_Out.setText("Check-Out");
        Check_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_OutActionPerformed(evt);
            }
        });
        jPanel1.add(Check_Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 190, 60));

        Check_In.setText("Check-in");
        Check_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_InActionPerformed(evt);
            }
        });
        jPanel1.add(Check_In, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 190, 60));

        Search1.setText("Busqueda de reservaciones");
        Search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search1ActionPerformed(evt);
            }
        });
        jPanel1.add(Search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 190, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed
        Registro_clientes v2 = new Registro_clientes(this, v1);
        v2.setVisible(true);
    }//GEN-LAST:event_RegistroActionPerformed

    private void HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HistorialActionPerformed

    private void reservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservacionActionPerformed
        Reservaciones v3 = new Reservaciones(this);
        v3.setVisible(true);
    }//GEN-LAST:event_reservacionActionPerformed

    private void Check_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_OutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Check_OutActionPerformed

    private void Check_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_InActionPerformed
        Check_In v5 = new Check_In(this, v1);
        v5.setVisible(true);
    }//GEN-LAST:event_Check_InActionPerformed

    private void Search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search1ActionPerformed
        Busqueda_reser v4 = new Busqueda_reser(this, v1);
        v4.setVisible(true);
    }//GEN-LAST:event_Search1ActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Check_In;
    private javax.swing.JButton Check_Out;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Historial;
    private javax.swing.JButton Registro;
    private javax.swing.JButton Search1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reservacion;
    // End of variables declaration//GEN-END:variables
}
